### PR TITLE
GeoMath and Serialization

### PR DESCRIPTION
**Pull request by davidair**
Added support for geo math (lat/long coordinates) and serialization for fast loading. Removed typemath registration to allow multiple maths of the same type (float).

### CODE REVIEW

**Comment by codeandcats** [comment]
:+1: Nice work David.

I've had a quick cursory look over the code. When I get some free time I'll merge it in.

**Comment by davidair** [comment]
Awesome! I've used your KdTree implementation to geo-locate a bunch of
photos, in conjunction with a world city list (
https://www.maxmind.com/en/free-world-cities-database). It took only 17
seconds to load over 3,000,000 cities into the KdTree and then the lookups
were very fast even without balancing. Once the tree was serialized, I was
able to save those 17 seconds and the tree now loads from file almost
instantaneously. Thank you for the great library!

David.

**Comment by codeandcats** [comment]
Thanks for your contribution David, sorry I took my time getting it in. Cheers

**Comment by davidair** [comment]
Cool, totally not a problem that it took time - it's hard to allocate time
to side projects :) Glad my changes made it in eventually!

**Comment by Wokker** [comment]
After i solved this problem my self I saw this pull request by Davidair. 
I solved it by converting the lat and long to XYZ coordinates en made 3 dimensional tree. Is there any notifying  difference with the solution of Davidair?

(x = cos(toRadians(latitude)) * cos(toRadians(longitude))
y = cos(toRadians(latitude)) * sin(toRadians(longitude))
z = sin(toRadians(latitude)))

**Pull request merged**
