### PR TITLE
Add support for .Net Core and .Net Standard

### PR DESCRIPTION
**Pull request by RobThree**
Hi!

Would you please consider merging this PR? It adds support for .Net Core and .Net Standard. I've converted the project to the new format, it also (still) builds a NuGet package (but now with a whole range of supported frameworks), and besides that I did a little bit of cleanup (removed & sorted all usings statements and got rid of some code analyzer tips/hints about (minor) code improvements).

I also up'd the version to 1.4.0 so you should be good to go and publish an updated NuGet package without trouble 😃 

Thanks for the great library. I'm porting my [NGeoNames](https://github.com/RobThree/NGeoNames) library to .Net Core and .Net Standard and since I've had a dependency on your KdTree library since day one I really need it to support .Net Core and .Net Standard too 😉 I could continue with a forked build but I prefer this way 😉

### CODE REVIEW

**Comment by codeandcats** [comment]
Hi Rob,

Thanks very much for doing this. I appreciate it especially as I haven't worked in dotnet for a couple years now so not in a great position to maintain this library. Since you're actually using the library and seemingly working in this space, how would you feel about me adding you as a contributor?

Thanks,
Ben

**Comment by RobThree** [comment]
Hi Ben,

> Since you're actually using the library and seemingly working in this space, how would you feel about me adding you as a contributor?

Much appreciated. It's not necessary but if I can help (no promises though 😉 ) I'll try to where I can. You may want to add me (if you agree that is) to the [NuGet package owners](https://www.nuget.org/packages/KdTree/ManagePackageOwners) as well so I can publish new(er) packages. Then again, as a sort of "quality control" or "last barrier" you may choose not to. It's up to you.

Thanks for the quick response!

**Comment by codeandcats** [comment]
That all sounds ideal. 👍Please add yourself in the list of contributors in the package description, etc.

**Comment by RobThree** [comment]
Thanks for adding me. I don't seem to be able to merge [a PR](https://github.com/codeandcats/KdTree/pull/13) though:

> Only those with write access to this repository can merge pull requests.

Could you check my permissions? Thanks! 👍

**Comment by RobThree** [comment]
[**BAM!**](https://github.com/codeandcats/KdTree/pull/13)

We on fire man! 🔥 😜

**Comment by codeandcats** [comment]
Fist bump! 🤜💥🤛 😄 

So yeah feel free to make changes as you see fit (short of removing me as an npm/git owner or adding malicious code lol). I see you are an experienced dotnet dev and pretty prolific on nuget so I trust and respect you. 👍

Cheers

**Comment by RobThree** [comment]
[**Double bam!**](https://www.nuget.org/packages/KdTree/1.4.0) 🤜💥🤛 

> So yeah feel free to make changes as you see fit (short of removing me as an npm/git owner or adding malicious code lol).

No worries. Only maybe when I'm drunk. And I'm not drunk... Yet 🤣 😜 

> I see you are an experienced dotnet dev and pretty prolific on nuget so I trust and respect you.

You're making me blush! 😊 

Thanks for the quick responses. I'll try to see if I can do something about the open issues etc. and see if I can improve this when I have a bit of spare time. Again, no promises though 😉

**Pull request merged**
