### PR TITLE
Add double math class.

### PR DESCRIPTION
**Pull request by Wokker**
Added the doubleMath class as alternative for the Floatmath class. This will fix issue #8.

### CODE REVIEW

**Comment by RobThree** [comment]
Any chance this could be merged / released anytime soon? I currently [still have to include](https://github.com/RobThree/NGeoNames/blob/eaaa9c867411ddadfaf2bfffa73c0dab977d106d/NGeoNames/ReverseGeoCode.cs#L211) this myself (built against [1.0.2](https://www.nuget.org/packages/KdTree/1.0.2); would like to update to 1.2.0).

**Comment by codeandcats** [comment]
Sorry about that. I'll find time to look at this tonight and merge it in.

**Comment by RobThree** [comment]
No need to apologize! And no hurry. I was more sort of wondering if I should wait or put it in the next release.

**Comment by codeandcats** [comment]
So I revisited my Windows bootcamp partition for the first time in months and remembered that not only do I not have Visual Studio installed, but I also Windows started randomly freezing my Macbook Pro a while back.

Unfortunately I will not be able to merge this in tonight, _however_ I will make it my mission to get this in sometime over the next 14 days, even if it means commandeering my girlfriends gaming machine (which is no small feat given the latest WoW expansion just came out 😜).

**Comment by RobThree** [comment]
Take your time. And leave the GF alone :wink: I'm in no hurry.

**Pull request merged**
